### PR TITLE
Feat/add wafw00f

### PR DESCRIPTION
**Pull request by cyrinux**

### CODE REVIEW

**Comment by cyrinux** [comment]
Hmm i think this PR need some sed on the input file that got some too much dots after httprobe

**Comment by drtychai** [comment]
Thanks! I'll take a look at this (hopefully) this week ^^

From just a quick glance, there's some stuff I would prefer to not change (e.g., changing tab sizes to 2 chars from 4, single quotes to double quotes, etc.); just a personal coding preference. Once I take an in-depth look, I'll have more concrete notes to share :)

**Comment by cyrinux** [comment]
Yes, sorry, i got also my habit with some code formatter in my kakoune, i use black formatter btw for python i like a lot.
Maybe we can try to use config like this in bottom of file, `# vim: tabstop=4 expandtab shiftwidth=4 softtabstop=4` ?

**Comment by drtychai** [comment]
@cyrinux Thank you for the PR! I finally got some free time and made the appropriate format changes, as well as a tool review. This looks good -- merging into `development` branch. 

Also, I'll try to come up with a good vim formatting command for next time :)

**Pull request merged**
